// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfYCYChFWnYMatNKmeh_ftZYC89TxpIqM',
    appId: '1:571703132580:web:fcfeea257c5093f8860131',
    messagingSenderId: '571703132580',
    projectId: 'projectandro-ed222',
    authDomain: 'projectandro-ed222.firebaseapp.com',
    databaseURL: 'https://projectandro-ed222-default-rtdb.firebaseio.com',
    storageBucket: 'projectandro-ed222.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAihsEYH3gwRyM2JC4tjLtJFRioPg7MxPY',
    appId: '1:571703132580:android:b6488cba2ea8ad08860131',
    messagingSenderId: '571703132580',
    projectId: 'projectandro-ed222',
    databaseURL: 'https://projectandro-ed222-default-rtdb.firebaseio.com',
    storageBucket: 'projectandro-ed222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4W0outSSggr0E4bCEzs4qAFhSamGu4-E',
    appId: '1:571703132580:ios:20d69e41c8e74f7f860131',
    messagingSenderId: '571703132580',
    projectId: 'projectandro-ed222',
    databaseURL: 'https://projectandro-ed222-default-rtdb.firebaseio.com',
    storageBucket: 'projectandro-ed222.appspot.com',
    iosBundleId: 'com.example.pixelNest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4W0outSSggr0E4bCEzs4qAFhSamGu4-E',
    appId: '1:571703132580:ios:20d69e41c8e74f7f860131',
    messagingSenderId: '571703132580',
    projectId: 'projectandro-ed222',
    databaseURL: 'https://projectandro-ed222-default-rtdb.firebaseio.com',
    storageBucket: 'projectandro-ed222.appspot.com',
    iosBundleId: 'com.example.pixelNest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfYCYChFWnYMatNKmeh_ftZYC89TxpIqM',
    appId: '1:571703132580:web:7cb9df3934f2801e860131',
    messagingSenderId: '571703132580',
    projectId: 'projectandro-ed222',
    authDomain: 'projectandro-ed222.firebaseapp.com',
    databaseURL: 'https://projectandro-ed222-default-rtdb.firebaseio.com',
    storageBucket: 'projectandro-ed222.appspot.com',
  );
}
